### ISSUE TITLE
Encoding::UndefinedConversionError: "\xF0" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by elado** [intridea/grape#786]
I get the following error when I post a file with extra body that contains UTF-8 chars, and trying to convert those fields to JSON:

```
Encoding::UndefinedConversionError: "\xF0" from ASCII-8BIT to UTF-8
	.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/hashie-3.3.1/lib/hashie/hash.rb:42:in `encode'
	.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/hashie-3.3.1/lib/hashie/hash.rb:42:in `to_json'
	.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/hashie-3.3.1/lib/hashie/hash.rb:42:in `to_json'
```

Example app:

```ruby
require 'grape'
require 'json'

class API < Grape::API
  format :json

  post do
    puts params[:body].to_json
  end
end

run API
```

Run with `bundle exec rackup -p3000`

Call with

```bash
curl -X POST --form "body=😈&file=@file.jpg" http://localhost:3000 --trace-ascii dump.txt
```

In this case the 😈 is an emoji (not sure it's visible here).

Since it's a multipart/form-data I can't set charset on the Content-Type as the request generates a random boundary. I'm not even sure it'd help.

Any suggestions?

**Comment by chrisdebruin** [comment]
have the same issue, anybody resolved this problem without doing the force_encoding hack?

**Comment by dm1try** [comment]
@chrisdebruin , try update your `rack` to version `~> 1.6.0`.
Seems like this encoding problem is fixed [here](https://github.com/rack/rack/commit/5c7f9c61f84d52d455f99dd783bbc4a1d33f625d#diff-cf7f8c59e9c8e133ae3a83ab322da380R59).

BTW, @sbounmy is right, `rfc2388` says 
> As with all multipart MIME types, each part has an optional
   "Content-Type", which defaults to text/plain.  If the contents of a
   file are returned via filling out a form, then the file input is
   identified as the appropriate media type, if known, or
   "application/octet-stream".  If multiple files are to be returned as
   the result of a single form entry, they should be represented as a
   "multipart/mixed" part embedded within the "multipart/form-data".

 You can use `curl` command to check it out (it has `type` option for the `form` requests)
`curl -X POST -F "body=😈;type=text/plain; charset=UTF-8" http://localhost:3000` (try another encoding because `UTF-8` is set by default, see the commit above)
It will work if `rack ~>1.6.0` is used .

I'll close this.

**Comment by chrisdebruin** [comment]
@dm1try thnx works for me
