### ISSUE TITLE
Allow definition of custom types

### ISSUE THREAD

**Issue by lpil** [intridea/grape#993]
Hello! Thank you for Grape. :)

We would like to be able to do something like this:

```ruby
params do
  requires :id, type: UUID, desc: 'Content id.'
end
```

Rather then set the type as String, and then validate the format of that string. We realise we can achieve the same result using validators, but we think this would be a more elegant, declarative syntax.

Is this possible?

Thanks,
Louis

**Comment by dblock** [comment]
It probably is with a bit of work - you need to dig through the implementation because `type` is something special. Grape's validation is based on Virtus (https://github.com/solnic/virtus), so I think defining a Virtus type for UUID would be sufficient. I don't know exactly how, will leave this open as a feature request.

**Comment by dblock** [comment]
Closed via https://github.com/intridea/grape/pull/1039.
